### ISSUE TITLE
Network is out of time.

### ISSUE THREAD

**Issue by ZGarry** [exewin/card-game#2]
Sorry, it is my first time to use unity. 
The following is the question. The network is out of time.
Then,  the complie is not successful. 
![捕获](https://user-images.githubusercontent.com/43488431/57345478-94095100-717d-11e9-8916-511b7b187b3b.PNG)

If I delete the code where have wrong, the game can run successfully.

**Comment by exewin** [comment]
Sorry for late answer.
Multiplayer is in this project was only an experiment so it's very buggy. I don't work on this project anymore, so I can't guarantee that scripts will work on new versions on Unity. 
Anyways, thank you for interest.
